[package]
name = "simple_fast_regex"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "simple_fast_regex"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
rayon = "1.10.0"
regex = "1.10.5"
